### ISSUE TITLE
Not able to connect to a device.

### ISSUE THREAD

**Issue by gotirahul96** [LenhartStephan/flutter_blue_classic#1]
Hey, I'm trying to connect to a classic Bluetooth device, but I'm getting this exception.

E/flutter (17700): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(connect_error, read failed, socket might closed or timeout, read ret: -1, null, null)
E/flutter (17700): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (17700): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (17700): <asynchronous suspension>
E/flutter (17700): #2      MethodChannelFlutterBlueClassic.connect (package:flutter_blue_classic/src/flutter_blue_classic_method_channel.dart:92:15)
E/flutter (17700): <asynchronous suspension>
E/flutter (17700): #3      _MyAppState.build.<anonymous closure>.<anonymous closure> (package:flutter_blue_classic_example/main.dart:105:78)
E/flutter (17700): <asynchronous suspension>

It would be great if you could please help sort this out as soon as possible.Thank you in advance.

**Comment by LenhartStephan** [comment]
Hey, I have just updated the sample app. Can you please try connecting via this one?
Also: What kind of device are you trying to connect?

**Comment by gotirahul96** [comment]
We are trying to connect my car's Bluetooth system. It's a classic device. It's getting paired but not getting connected. It's giving the same exception as before. As we look into the commit, there are changes in the scanning part only. Can you look into the connection part as well?

**Comment by gotirahul96** [comment]
> We are trying to connect my car's Bluetooth system. It's a classic device. It's getting paired but not getting connected. It's giving the same exception as before. As we look into the commit, there are changes in the scanning part only. Can you look into the connection part as well?

I was able to find the problem. We are not able to connect to the socket. and hence giving this issue. so maybe we can find somewhere around that.

**Comment by LenhartStephan** [comment]
Your logs suggest, that the remote device is not accepting the connection.
I can currently not reproduce your error. I've tested a connection with a bluetooth printer and a [simple rfcomm BL server using pybluez](https://github.com/pybluez/pybluez/blob/master/examples/simple/rfcomm-server.py) and both worked like expected.

**Comment by fazilmuhammad** [comment]
Hi Guys.Any update of this issues yet.I have the same problem ,but for i cant connect to OrangePI bluetooth

**Comment by LenhartStephan** [comment]
At the moment, I do not have enough information about the issue to help, since I can not reproduce your error. Like, what do you want to connect to? And I dont mean the device itself, since that is quite meaningless, but rather what Software. Do you get any logs, errors, ...

**Comment by fazilmuhammad** [comment]
I want to connect to OrangePI Bluetooth that is actually a Avalible for BLE and Classice but the error shows that OrangePI rejected the connection.Is anything i can do?, Like a special setting up on the apps , just for devices like OrangePI or it is simply impossible for me to connect to OrangePI bluetooth?

**Comment by LenhartStephan** [comment]
Again: the orange pi is, as far as I know a raspberry pi clone, so it‘s just a device. You cannot just connect to a device via bluetooth like that. You would need to run a kind of bluetooth server on the pi, that accepts a connection. Then both devices can use that connection to talk to each other.

**Comment by bipinrawatCyno** [comment]
I AM trying to connect a android tv but i am getting this error  -     


E/flutter (10787): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(connect_error, read failed, socket might closed or timeout, read ret: -1, null, null)
E/flutter (10787): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (10787): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (10787): <asynchronous suspension>
E/flutter (10787): #2      MethodChannelFlutterBlueClassic.connect (package:flutter_blue_classic/src/flutter_blue_classic_method_channel.dart:109:9)
E/flutter (10787): <asynchronous suspension>
E/flutter (10787): #3      _MainScreenState._connectToDevice (package:flutter_blue_classic_example/main.dart:90:20)
E/flutter (10787): <asynchronous suspension>

**Comment by enes-vural** [comment]
Is there any change? I had this error too

**Comment by LenhartStephan** [comment]
Hey, for a proper error report, I need the following information:
- What device (most importantly the Android version) are you using
- To what device do you want to connect (Device type and more importantly Software => What is the Bluetooth server? E.g: On a label printer that would be the firmware of the printer. On a raspberry pi or android tv there would need to be a special software running and awaiting a connection. You cannot "_just connect to a raspberry pi_".)
- Whats the specific error log?

**Comment by Eloks7** [comment]
@LenhartStephan Does this mean I can't connect to a phone's bluetooth? Also is it possible for me to connect two apps built with this package.

**Comment by enes-vural** [comment]
> @LenhartStephan Does this mean I can't connect to a phone's bluetooth? Also is it possible for me to connect two apps built with this package.

I tried to connect my mobile phone's bluetooth and got this error but bluetooth classic packages works with other devices like (hc05-hc06) bluetooth classic modules.
Probably you can not connect phone's bluetooth also you can check flutter_blue_plus package for your mobile phone.

**Comment by Eloks7** [comment]
@TrSaka Yeah got same error, flutter_blue_plus doesn't detect phones at all.

**Comment by enes-vural** [comment]
> @TrSaka Yeah got same error, flutter_blue_plus doesn't detect phones at all.

sorry for misinformation you're right Bluetooth LE doesn't work with mobile devices. Bluetooth LE does not work with mobile devices. I can connect other classic modules, but I cannot connect mobile phones with Classic.

**Comment by LenhartStephan** [comment]
So, you can connect your phone to another phone via bluetooth (classic), but the other device must have a bluetooth server running. Currently this package is not providing the functionallity to create a bluetooth server, but that _might_ be added in the future.
If you want to experiment with a simple bluetooth server connection, you can setup a basic [python bluetooth server with pybluez](https://github.com/pybluez/pybluez/blob/master/examples/simple/rfcomm-server.py).
(Note: I belive this example is just supported on Windows and Linux)

**Comment by Cyber-Nut** [comment]
I am getting the same error: PlatformExceoption(connect_error, read failed, socket might be closed or timeout, read ret: -1, null, null), I am trying to connect with esp32 with my mobile device. It got paired successfully but couldn't connect.

**Comment by Creiger** [comment]
Well i had the same problem without fine location enabled. But when i enabled fine location, it works. I dont know why i need to use it for audio device.

**Comment by Cyber-Nut** [comment]
Hey man, can you share me your repo?

**Comment by LenhartStephan** [comment]
As always my first question: What code is running on your esp32? You need to have a bluetooth server running.

**Comment by Cyber-Nut** [comment]
I have set up the server on the esp32, let's keep the esp32 aside for a second, even though I cannot set up a connection to any Bluetooth speakers or earphones! It instantly gives the error Platform Exception

**Comment by LenhartStephan** [comment]
Speakers or Earphones do not act as a bluetooth server and you therefore can not create a Client connection to them. As I mentioned before, this package only provides support for Bluetooth Classic and Client connections.
Besides, what data would you want to send to a speaker anyway? I would guess Audio, so you would rather want to take a look the Android API for Bluetooth Low Energy Audio.

**Comment by datpt11** [comment]
Barcode scanner also has the same error
